/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "error-container": "#93000a",
          "glass-fill": "rgba(255, 255, 255, 0.08)",
          "on-tertiary-container": "#432100",
          "deep-navy": "#06090F",
          "on-primary-container": "#00275f",
          "on-primary": "#002d6c",
          "surface-container-low": "#181b25",
          "tertiary-container": "#d87802",
          "on-primary-fixed": "#001a43",
          "on-secondary-container": "#fbfdff",
          "error": "#ffb4ab",
          "surface-container-high": "#262a34",
          "tertiary-fixed": "#ffdcc2",
          "surface-variant": "#31353f",
          "on-error-container": "#ffdad6",
          "surface-tint": "#afc6ff",
          "on-surface-variant": "#c2c6d6",
          "surface-container-highest": "#31353f",
          "on-tertiary-fixed-variant": "#6d3a00",
          "surface": "#0f131c",
          "background": "#0f131c",
          "outline": "#8c909f",
          "on-surface": "#dfe2ef",
          "primary-fixed-dim": "#afc6ff",
          "surface-dim": "#0f131c",
          "secondary-fixed-dim": "#78d1f9",
          "outline-variant": "#424753",
          "primary": "#afc6ff",
          "on-background": "#dfe2ef",
          "liquid-blue-glow": "rgba(79, 140, 255, 0.4)",
          "inverse-primary": "#0059c6",
          "on-tertiary-fixed": "#2e1500",
          "primary-container": "#528dff",
          "on-primary-fixed-variant": "#004398",
          "on-error": "#690005",
          "surface-container-lowest": "#0a0e17",
          "inverse-surface": "#dfe2ef",
          "secondary-fixed": "#bee9ff",
          "glass-stroke": "rgba(255, 255, 255, 0.12)",
          "surface-bright": "#353943",
          "on-tertiary": "#4d2700",
          "secondary": "#78d1f9",
          "surface-container": "#1c1f29",
          "secondary-container": "#027ea3",
          "on-secondary-fixed": "#001f2a",
          "inverse-on-surface": "#2c303a",
          "on-secondary-fixed-variant": "#004d65",
          "tertiary-fixed-dim": "#ffb77b",
          "tertiary": "#ffb77b",
          "primary-fixed": "#d9e2ff",
          "on-secondary": "#003546"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "unit": "8px",
          "gutter-workspace": "24px",
          "panel-padding": "24px",
          "container-margin": "40px"
      },
      "fontFamily": {
          "body-lg": ["Inter"],
          "headline-sm": ["Manrope"],
          "display-lg": ["Manrope"],
          "body-md": ["Inter"],
          "label-caps": ["JetBrains Mono"],
          "code-block": ["JetBrains Mono"],
          "headline-md": ["Manrope"]
      },
      "fontSize": {
          "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
          "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "code-block": ["14px", {"lineHeight": "22px", "fontWeight": "450"}],
          "headline-md": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
